name: BetterNotice
version: '${version}'

main: com.ksiu.better.BetterNotice
api-version: '1.21.1'
load: POSTWORLD
depend: [BetterHud]

commands:
  공지:
    description: "공지 팝업을 출력합니다."
    usage: "/공지 [내용]"
