name: BetterNotice
version: '${version}'

main: com.ksiu.better.BetterNotice
api-version: '1.21.1'
load: POSTWORLD
depend: [BetterHud]
softdepend: [MythicMobs]

commands:
  bnreload:
    description: "betterNotice의 설정 파일을 재로드합니다."
    usage: "/bnreload"

  공지:
    description: "공지 팝업을 출력합니다."
    usage: "/공지 [내용]"
